export const products = [
  {
    id: 1,
    name: "Nissan",
    availableName: ["Nissan"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:90,
    price: 120,
    offPrice: 120,
    discount: null,
    image: "https://s2.uupload.ir/files/car_(3)_vykc.png",
  },
  {
    id: 2,
    name: "Rols - royce",
    availableName: ["Rols"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:100,
    price: 22000,
    offPrice: 120,
    discount: null,
    image: "https://s2.uupload.ir/files/car_(3)_vykc.png",
  },
  {
    id: 3,
    name: "Jeep",
    availableName: ["Jeep"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:90,
    price: 120,
    offPrice: 120,
    discount: null,
    image: "https://s2.uupload.ir/files/car_(3)_vykc.png",
  },
  {
    id: 4,
    name: "Jeep",
    availableName: ["Jeep"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:60,
    price: 1220,
    offPrice: 120,
    discount: null,
    image: "https://s2.uupload.ir/files/car_(3)_7vw1.png",
  },
  {
    id: 5,
    name: "Santafe",
    availableName: ["Santafe"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:70,
    price: 1720,
    offPrice: 120,
    discount: 1898,
    image: "https://s2.uupload.ir/files/car_(4)_iqb.png",
  },
  {
    id: 6,
    name: "Santafe",
    availableName: ["Santafe"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:70,
    price: 1720,
    offPrice: 120,
    discount: null,
    image: "https://s2.uupload.ir/files/car_p3wb.png",
  },
  {
    id: 7,
    name: "Jeep",
    availableName: ["Jeep"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:90,
    price: 120,
    offPrice: 120,
    discount: null,
    image: "https://s2.uupload.ir/files/cars(1)_rp7c.png",
  },
  {
    id: 8,
    name: "Jeep",
    availableName: ["Jeep"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:90,
    price: 5220,
    offPrice: 120,
    discount: null,
    image: "https://s2.uupload.ir/files/cars(2)_vlg5.png",
  },
  {
    id: 9,
    name: "Jeep",
    availableName: ["Jeep"],
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    people:4,
    gas:90,
    price: 120,
    offPrice: 120,
    discount: 140,
    image: "https://s2.uupload.ir/files/car_(3)_vykc.png",
  },
];
